### ISSUE TITLE
Context.CreateSubOrchestration Throws Activity version not Found

### ISSUE THREAD

**Issue by Selekena** [Azure/durabletask#1111]
I am trying to create a suborchestration with our Netherite DTFx and its throwing this exception. Questions:

1. Are suborchestrations handled like Activites? If that's the case are they handled different to allow them to have activities of their own?
2. How do I get this version registered? Right now we have set up the .Net app by registering all the orchestrations and their INameVersion* mappings i.e.

_ = services.AddTransient<SubscriptionLifecycleRetryingOrchestration, SubscriptionLifecycleRetryingOrchestration>();
**...**
services.AddSingleton<INameVersionObjectManager<TaskOrchestration>>(serviceProvider => new OrchestrationManager(
		new OrchestrationNameVersionTypeMap[]
		{
			**...**
			new OrchestrationNameVersionTypeMap<SubscriptionLifecycleUpdateOrchestration>(typeof(SubscriptionLifecycleUpdateOrchestration).ToString(), "v05-01-2024"),
		}, 

later initiated like this,

result = await context.CreateSubOrchestrationInstance<SubscriptionLifecycleOrchestrationResult>(nameof(SubscriptionLifecycleUpdateOrchestration), "v05-01-2024", context.OrchestrationInstance.InstanceId, input);

3. Should I register it instead as Activity, assuming (1) is true?

TaskActivityDispatcher-14168daa1d4e4098831e7c80455f15d1-265: Unhandled exception with work item '1056': **DurableTask.Core.Exceptions.TypeMissingException: TaskActivity Microsoft.Azure.EdgeProvisioning.EdgeProvisioningService.Orchestrations.SubLifecycleOrchestrations.SubscriptionLifecycleUpdateOrchestration version  was not found**
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass14_1.<<OnProcessWorkItemAsync>b__2>d.MoveNext() in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 216
--- End of stack trace from previous location ---
   at DurableTask.Core.TaskActivityDispatcher.OnProcessWorkItemAsync(TaskActivityWorkItem workItem) in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 289
   at DurableTask.Core.TaskActivityDispatcher.OnProcessWorkItemAsync(TaskActivityWorkItem workItem) in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 289
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 459

Backing off for 10 seconds

**Comment by Selekena** [comment]
I found my issue. I had a typeof() vs nameof() confusion. Used them both on either end of a DI registration and client call.
