### ISSUE TITLE
The entity received an unexpected event type of type 'OrchestratorStarted'.

### ISSUE THREAD

**Issue by alex-ht-work** [Azure/durabletask#1126]
I am getting this error from a durable function app: 

> TaskEntityDispatcher-8b857fa56dca4e659571eff6f1729b4e-0: Unhandled exception with work item '@uapiextract@ffh': DurableTask.Core.Exceptions.EntitySchedulerException: The entity with instanceId '@uapiextract@ffh' received an unexpected event type of type 'OrchestratorStarted'. This is not a valid entity message. This is a framework-internal error, please report this issue in the GitHub repo: 'https://github.com/Azure/durabletask/'
   at DurableTask.Core.TaskEntityDispatcher.DetermineWork(OrchestrationRuntimeState runtimeState, SchedulerState& schedulerState, Work& batch) in /_/src/DurableTask.Core/TaskEntityDispatcher.cs:line 568
   at DurableTask.Core.TaskEntityDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskEntityDispatcher.cs:line 241
   at DurableTask.Core.TaskEntityDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskEntityDispatcher.cs:line 377
   at DurableTask.Core.TaskEntityDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskEntityDispatcher.cs:line 122
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 373
> Backing off for 10 seconds until 5 successful operations

That used to be an in-process .Net 6 app, and I have converted it into .Net 8 isolated worker function app. The Durable Task framework API has changed, and so I had to refactor it.

I call the entity from an orchestration using `TaskOrchestrationContext.Entities.CallEntityAsync` (though I am not sure if I get the error at that moment or not).

Please let me know what kind of information you may need; I will do my best to provide all the details.

SDK version: azurefunctions: 4.34.2.22820

**Comment by alex-ht-work** [comment]
Found the same issue reported before, and it has a resolution here: https://github.com/Azure/durabletask/issues/1095

Closing this as a duplicate.
