### ISSUE TITLE
Parsing errors while DTFx processes the messages from queue in latest version of DurableTask.AzureStorage 2.0.0-rc.2.

### ISSUE THREAD

**Issue by Iamjithender** [Azure/durabletask#1141]
Hii, 
We started consuming the 2.0.0-rc.2 version of DurableTask.AzureStorage nuget as previous versions contain reference of the deprecated versions of "WindowsAzure.Storage".

After consuming the nuget we deployed in the ECY Canary region for testing. After deployment, we started encountering the Json parsing issues while dtfx processes the queue messages. "Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.". 

Full exception message with stack trace: 

```
An error occurred while processing messages on springboot-workitems: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at DurableTask.AzureStorage.Utils.DeserializeFromJson[T](JsonSerializer serializer, String jsonString) in /_/src/DurableTask.AzureStorage/Utils.cs:line 202
   at DurableTask.AzureStorage.MessageManager.DeserializeQueueMessageAsync(QueueMessage queueMessage, String queueName, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/MessageManager.cs:line 176
   at DurableTask.AzureStorage.Messaging.WorkItemQueue.GetMessageAsync(CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Messaging/WorkItemQueue.cs:line 48
```

   
We started encountering these issues after updating to the "2.0.0-rc.2", prior to that we didn't observe these issues. Let me know if you need anything further.

**Comment by saurav-microsoft** [comment]
Can you also attach the message from the queue ?

**Comment by davidmrdavid** [comment]
There's a known parsing error in the -rc.2 package - in particular, it is unable to de-serialize messages generated by the `1.x` package. Can you try upgrading to rc.3, that should be backwards-compatible.

Please note that the `-rc` packages are not production ready, so I cannot recommend using them in production. The GA package of the `2.x` track is about to be released. I'd hold off

**Comment by Iamjithender** [comment]
Thanks @davidmrdavid for updating us with the details. 
Okay sure, we will wait for 2.x GA version package release.

**Comment by Iamjithender** [comment]
> Can you also attach the message from the queue ?

Hey Saurav, 
I couldn’t get the message from queue, I took jit access and tried accessing the queue but I couldn’t find any messages in queue.

**Comment by saurav-microsoft** [comment]
@Iamjithender I had a similar issue as well. Just wanted to take a look at your message and see if the issue is same, 
s
If your queue message was hidden (controlled by visibility timeout config), it will become visible when the timeout happens

**Comment by nytian** [comment]
Just an update that the GA version of DTFx.AzureStorage v2 is published in nuget: https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/2.0.0
