### ISSUE TITLE
some error or not incompatibility when publish singlefile

### ISSUE THREAD

**Issue by AiHaibara** [Azure/durabletask#1174]
System.TypeInitializationException: The type initializer for 'DurableTask.AzureStorage.Utils' threw an exception.
 ---> System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at DurableTask.AzureStorage.Utils..cctor() in /_/src/DurableTask.AzureStorage/Utils.cs:line 32
   --- End of inner exception stack trace ---
   at DurableTask.AzureStorage.AzureStorageOrchestrationServiceSettings..ctor() in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationServiceSettings.cs:line 38

at 
 ```
  var settings = new AzureStorageOrchestrationServiceSettings
            {
                StorageAccountClientProvider = new StorageAccountClientProvider(connString)
```

net8.0
```
  <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" Version="2.0.1" />
  <PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="3.0.0" />
```

when using 
`dotnet publish -p:PublishSingleFile=true -c Release -r osx-x64 --self-contained false`

it will throw the error like before

but when it using 
`    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
`
it will ok for it

**Comment by cgillum** [comment]
Looks like publishing to a single file breaks our logic which tries to get the version of the current assembly.
