### ISSUE TITLE
AzureStorageOrchestrationService throws container not found exception in TaskHubWorker.Start() 

### ISSUE THREAD

**Issue by andrewwang2015** [Azure/durabletask#310]
When running `TaskHubWorker` with `AzureStorageOrchestrationService`, if the lease container does not currently exist, method `startAsync()` throws storage exception. 

```
Exception has occurred: CLR/Microsoft.WindowsAzure.Storage.StorageException
An unhandled exception of type 'Microsoft.WindowsAzure.Storage.StorageException' occurred in System.Private.CoreLib.dll: 'The specified container does not exist.'
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.<ListBlobsSegmentedAsync>d__61.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.<ListLeasesAsync>d__20.MoveNext() in C:\Users\ANDRWAN\Desktop\durabletask\src\DurableTask.AzureStorage\Partitioning\BlobLeaseManager.cs:line 111
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DurableTask.AzureStorage.Partitioning.PartitionManager`1.<InitializeAsync>d__15.MoveNext() in C:\Users\ANDRWAN\Desktop\durabletask\src\DurableTask.AzureStorage\Partitioning\PartitionManager.cs:line 57
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<StartAsync>d__59.MoveNext() in C:\Users\ANDRWAN\Desktop\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 445
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskHubWorker.<StartAsync>d__19.MoveNext() in C:\Users\ANDRWAN\Desktop\durabletask\src\DurableTask.Core\TaskHubWorker.cs:line 126
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at durableTask.Program.Main(String[] args) in c:\Users\ANDRWAN\Desktop\sandbox\durableTask\Program.cs:line 49
```

**Comment by cgillum** [comment]
Sorry for the delay on this. Just to make sure I understand, the workaround is to call `AzureStorageOrchestrationService.CreateIfNotExistsAsync()` prior to calling `TaskHubWorker.StartAsync()`, right? I believe this is also a requirement for the Service Bus provider. I guess it doesn't have to be this way, but just wanted to make sure I understood the issue correctly.

**Comment by cgillum** [comment]
I went ahead and merged the PR for this. It will go out with the next release of DurableTask.AzureStorage (ETA mid-December).
