### ISSUE TITLE
ServiceBusException when using Service Bus Premium with .NET Core Project

### ISSUE THREAD

**Issue by shthakkar** [Azure/durabletask#370]
I'm getting this exception when using Service Bus Premium version & .NET CORE 2.2 Target Framework.

If I change the service bus to Standard version or change the .NET Framework to 4.6.1. The orchestration completes successfully. For the above said issue, the orchestration state is "Pending".

To re-create, attached sample project can be used, which uses the AverageCalculator from durabletask/DurableTask.Samples. 

serviceBusConnectionString, storageConnectionString and taskHubName should be modified in Program.cs. 

**NuGet Packages versions**

"DurableTask.Core" Version="2.0.0.6"
"DurableTask.ServiceBus" Version="2.0.0.6" 
"EnterpriseLibrary.SemanticLogging" Version="2.0.1406.1" 
"Microsoft.Azure.DurableTask.ServiceBus" Version="2.1.3" 
"Microsoft.Azure.ServiceBus" Version="4.1.1" 
 "WindowsAzure.Storage" Version="9.3.3" 

**Exception Details**
Exception: Microsoft.Azure.ServiceBus.ServiceBusException : The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:1c875715-d6a5-4eb8-839b-bbe5aa367228, TrackingId:6e0b54590000008900000ebc5e501c4c_G12_B32, SystemTracker:escalationsvc-test:Queue:escalationsvchub/orchestrator, Timestamp:2020-02-21T18:07:09
           at Microsoft.Azure.ServiceBus.MessageSession.OnSetStateAsync(Byte[] sessionState)
   at Microsoft.Azure.ServiceBus.MessageSession.OnSetStateInstrumentedAsync(Byte[] sessionState)
   at DurableTask.ServiceBus.Common.Abstraction.IMessageSession.SetStateAsync(Byte[] sessionState) in C:\source\durabletask\src\DurableTask.ServiceBus\Common\Abstraction\ServiceBusAbstraction.cs:line 140
   at DurableTask.ServiceBus.ServiceBusOrchestrationService.TrySetSessionStateAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, OrchestrationRuntimeState runtimeState, IMessageSession session) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 1560
   at DurableTask.ServiceBus.ServiceBusOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 658
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 427
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 116
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 312

I will appreciate any pointers to resolve this issue.

Please let me know if you have any questions or need any additional information.

Thanks,
Sakshar
[DTFNetCoreSample.zip](https://github.com/Azure/durabletask/files/4238376/DTFNetCoreSample.zip)

**Comment by shankarsama** [comment]
We are looking into this issue. @tkamesh will update this thread with details.

**Comment by tkamesh** [comment]
Both the packages "DurableTask.Core", "Microsoft.Azure.DurableTask.Core" have the dlls with same name "DurableTask.Core.dll". It is recommended to use the later package.
Similarly, "DurableTask.ServiceBus", "Microsoft.Azure.DurableTask.ServiceBus" packages have the dlls with same name "DurableTask.ServiceBus.dll". It is recommended to use the later package. First package doesn't support .net standard, .net core. 

In the application attached, it is referencing all four packages (directly and indirectly). As the dll names are same, which ever the file that copied at the last will be part of execution. 

It is recommended to remove the references of "DurableTask.Core", "DurableTask.ServiceBus" and consume  "Microsoft.Azure.DurableTask.Core" and "Microsoft.Azure.DurableTask.ServiceBus" packages.

**Comment by jeffli-microsoft** [comment]
@tkamesh I've been seeing similar issues with the netstd library. When I run my app without kicking off orchestrations, we're seeing ServiceBusTimeout exceptions. once we kick off orchestrations, we see messages in the orchestrator queue that fail to get picked up properly and eventually end up in the deadletter queue.

Here's the history of my experience:
- We have a working app with DTF targeting net472
- Porting this to netcore3.1 with the new library started causing issues
- Cloning the source libraries directly into the project I was able to start seeing service bus exceptions (timeouts without any orchestrations, and general exceptions once orchestrations started)
- After reverting to a branch where our app was still net472, I again brought the source libraries in and removed the .NET targets (forcing the libraries to refresh using netstd) and ran into similar problems
- I also pulled the calculator test app and tried @tkamesh 's suggestions and am seeing the exact same behavior (orchestrator messages ending up in deadletter queue)

Let me know if there's any other information I can help provide

**Comment by shthakkar** [comment]
Thank you @tkamesh for all your help in debugging the issue and finding the root cause of the issue. With latest fix in Service Bus code, I was able to validate the example code and our service code running successfully without any errors with Service Bus Premium and .NET Core. Closing the issue now. Please update this thread with more details about the root cause and the fix.

**Comment by maximebousquet** [comment]
@jeffli-microsoft I'm not sure if I get what solution you ended up going with? We are currently using DTF with .NET Core 2.2 and are having similar issues. Our `TaskCompletedEvents` keep ending up on the DLQ of the orchestrator queue., but weirdly enough, not all of them do.

**Comment by jeffli-microsoft** [comment]
@maximebousquet I was not able to resolve the issue. I am still running into the issue with the updated libraries so I will try to provide more information around my errors.
