### ISSUE TITLE
Wakup issue ?

### ISSUE THREAD

**Issue by xTeKillax** [Azure/durabletask#384]
Hello,

On our team we are using durable task framework to process the launch of different powershell scripts.
We are facing an issue we are not able to understand. Our worker is running 24/7 waiting for commands to be sent, be sometimes, after a long period without any activity, it gets lost.

Any command sent to the worker running durable task framework is lost and we get no reaction from the worker. We need to restart it and all the commands sent while it was in this state are lost.
Are we doing something wrong ?

Here is the part that send the command from the API :
```
var instance = await _workFlowManager.GetClient().CreateOrchestrationInstanceAsync("PowerShellOrchestration",
                    "V1",
                    domainEvent.Operation.Id.ToString(),
                    orchestratorInput);

                OrchestrationState taskResult = await _workFlowManager.GetClient().WaitForOrchestrationAsync(instance, TimeSpan.FromSeconds(5), CancellationToken.None);
```

And here is the StartAsync method code for the worker :
```
IOrchestrationServiceInstanceStore instanceStore = new AzureTableInstanceStore(taskHubName, storageConnectionString);

            var orchestrationServiceAndClient = new ServiceBusOrchestrationService(serviceBusConnectionString, taskHubName, instanceStore, null, null);
            
            await orchestrationServiceAndClient.CreateIfNotExistsAsync();

            _taskHub = new TaskHubWorker(orchestrationServiceAndClient);

            _taskHub.AddTaskOrchestrations(new NameValueObjectCreator<TaskOrchestration>("PowerShellOrchestration",
                "V1",
                typeof(CreateOperationOrchestration)));

            _taskHub.AddTaskActivities(new ObjectCreator<TaskActivity>[]
            {
                new WorkerObjectCreator<TaskActivity>(typeof(ChangeOperationStatusActivity), _mediatr),
                new WorkerObjectCreator<TaskActivity>(typeof(LaunchPowerShellActivity), _mediatr),
            });

            await _taskHub.StartAsync();
```

Thank's for your help

**Comment by ConnorMcMahon** [comment]
Which backend storage option are you using? Each backend has different owners, who should be able to speak more to what sort of bugs could cause this issue.

**Comment by cgillum** [comment]
It looks like it's the Service Bus backend, per that second code blurb. @simonporter might be the right person to take a quick look.

**Comment by xTeKillax** [comment]
We are using both Azure Service Bus and Azure Storage Table.
In Service Bus I can see the 3 queues created by DTF without problem and on Storage Table I do have HistoryInstance and JumpStart tables
I didn't see anything I could use to debug my problem using the data in Storage Table.

Thank's for your help guys :)

**Comment by simonporter** [comment]
Events are emitted as ETW events, you can sub subscribe to these for debugging.
Example here: https://github.com/Azure/durabletask/blob/master/samples/DurableTask.Samples/Program.cs#L48

**Comment by xTeKillax** [comment]
Thank's @simonporter 
I'll update with this piece of code and push it and wait for the problem to occur, it should occur on monday, after the weekend

**Comment by xTeKillax** [comment]
Hello,
The problem happend again yesterday. I wasn't able to remote debug (breakpoint did not trigger (white circle on VS)) and I couldn't see anything from the ObservableEventListener that @simonporter suggested to add.

The problem happened on INT environment and I don't know if it's simple coincidence or not, but the worker on PROD also stopped and it seems to be around the same time.
I'm wondering if there is something related to Azure Service Bus since we don't even get the commands when we restart the worker

**Comment by xTeKillax** [comment]
Hello guys,
Do you have any hint about this problem on your side ?

**Comment by xTeKillax** [comment]
I may have found something :

```
message : TaskOrchestrationDispatcher-8be5471ed48846cb97130c4f63c24c17-0: Exception while processing workItem e173686e-f87b-463d-29ef-08d7f007adfd
Exception: Microsoft.Azure.ServiceBus.ServiceBusException : 'sender1167' is closed
           at Microsoft.Azure.ServiceBus.MessageSession.OnSetStateAsync(Byte[] sessionState)
   at DurableTask.ServiceBus.Common.Abstraction.IMessageSession.SetStateAsync(Byte[] sessionState) in C:\source\durabletask\src\DurableTask.ServiceBus\Common\Abstraction\ServiceBusAbstraction.cs:line 141
   at DurableTask.ServiceBus.ServiceBusOrchestrationService.TrySetSessionStateAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, OrchestrationRuntimeState runtimeState, IMessageSession session) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 1590
   at DurableTask.ServiceBus.ServiceBusOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 791
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 431
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 116
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 377
```

I'll investigate this but if you guys are still here and have any idea, you are welcome :)
