### ISSUE TITLE
ArgumentException: A lease ID must be specified when changing a lease

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#406]
I see this error pop up periodically during investigations. I have not investigated the impact of this error, but it should be fixed if for no reason except to remove noise from logs.

```
System.ArgumentException: A lease ID must be specified when changing a lease.
Parameter name: accessCondition
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseImpl(BlobAttributes attributes, String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options)
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseAsync(String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseAsync(String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseAsync(String proposedLeaseId, AccessCondition accessCondition)
at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.AcquireAsync(BlobLease lease, String owner) in C:\source\durabletask\src\DurableTask.AzureStorage\Partitioning\BlobLeaseManager.cs:line 225
at DurableTask.AzureStorage.Partitioning.PartitionManager`1.AcquireLeaseAsync(T lease) in C:\source\durabletask\src\DurableTask.AzureStorage\Partitioning\PartitionManager.cs:line 490
```

**Comment by sehcheese** [comment]
@cgillum Any updates on this? Does this impact the amount of time it takes a Durable Function to complete?

**Comment by ppozeti** [comment]
Noticed same error happening a couple of times. I'm using Microsoft.Azure.WebJobs.Extensions.Storage 3.0.4. What about you @sehcheese ?
Should we be worried?

**Comment by cgillum** [comment]
No update yet, but I’m not aware of any runtime impact. I suspect it may be happening when new VM instances are spun up out as part of some lease transitions, but not during normal operation. However, more investigation is needed to confirm.

**Comment by sehcheese** [comment]
@ppozeti We are on Microsoft.Azure.WebJobs.Extensions.Storage 3.0.11.
@cgillum Thanks. Just noticed this as I was observing the Log Stream in Azure and wondered about it.

**Comment by akratikamboj** [comment]
We are also receiving this error periodically. This is creating unnecessary noise in the error logs if not impacting the application. Is there any fix to it?

**Comment by cgillum** [comment]
@amdeel do you have any ideas about this error message? I see it shows up in the v1.10.1 package version as well.

```
Error in intent lease acquisition: System.ArgumentException: A lease ID must be specified when changing a lease. (Parameter 'accessCondition')
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseImpl(BlobAttributes attributes, String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseAsync(String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at DurableTask.AzureStorage.Storage.Blob.<>c__DisplayClass20_0.<ChangeLeaseAsync>b__0(OperationContext context, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Storage/Blob.cs:line 121
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId) in /_/src/DurableTask.AzureStorage/TimeoutHandler.cs:line 60
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId)
   at DurableTask.AzureStorage.Storage.Blob.ChangeLeaseAsync(String proposedLeaseId, String currentLeaseId) in /_/src/DurableTask.AzureStorage/Storage/Blob.cs:line 120
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.AcquireAsync(BlobLease lease, String owner) in /_/src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs:line 169
   at DurableTask.AzureStorage.Partitioning.LeaseCollectionBalancer`1.AcquireLeaseAsync(T lease) in /_/src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs:line 540
```

```kusto
DurableFunctionsEvents
| where TIMESTAMP > ago(3d)
| where ProviderName == "DurableTask-AzureStorage"
| where Details has "A lease ID must be specified when changing a lease."
| where ExtensionVersion == "1.10.1"
| project TIMESTAMP, EventStampName, RoleInstance, Pid, Tid, Level, TaskName, PartitionId, EventType, TaskEventId, Age, RuntimeStatus, NewEvents, EventCount, DequeueCount, Details, LatencyMs, TaskHub, Account, ExtensionVersion 
| take 10
```

**Comment by cgillum** [comment]
Reactivating per this comment: https://github.com/Azure/durabletask/pull/709#issuecomment-1910442976

**Comment by petercwq** [comment]
We are on Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.5, which uses DurableTask.AzureStorage.dll 1.17.4.
And I see this error captured by app insights quite often. Any suggestions?

```
durabletasks-control-01: Error in intent lease acquisition: System.ArgumentException: A lease ID must be specified when changing a lease. (Parameter 'accessCondition')
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseImpl(BlobAttributes attributes, String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ChangeLeaseAsync(String proposedLeaseId, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at DurableTask.AzureStorage.Storage.Blob.<>c__DisplayClass20_0.<ChangeLeaseAsync>b__0(OperationContext context, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Storage/Blob.cs:line 121
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId) in /_/src/DurableTask.AzureStorage/TimeoutHandler.cs:line 56
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force)
   at DurableTask.AzureStorage.Storage.Blob.ChangeLeaseAsync(String proposedLeaseId, String currentLeaseId) in /_/src/DurableTask.AzureStorage/Storage/Blob.cs:line 120
   at DurableTask.AzureStorage.Partitioning.BlobLeaseManager.AcquireAsync(BlobLease lease, String owner) in /_/src/DurableTask.AzureStorage/Partitioning/BlobLeaseManager.cs:line 171
   at DurableTask.AzureStorage.Partitioning.LeaseCollectionBalancer`1.AcquireLeaseAsync(T lease) in /_/src/DurableTask.AzureStorage/Partitioning/LeaseCollectionBalancer.cs:line 548
```
