### ISSUE TITLE
System.NullReferenceException in OrchestrationSessionManager, line 217

### ISSUE THREAD

**Issue by chrisw000** [Azure/durabletask#457]
The latest code for OrchestrationSessionManager, at line 208, looks like this:

```
                        if (executionId == null || session.Instance.ExecutionId == executionId)
                        {
                            List<MessageData> pendingMessages;
                            if (!existingSessionMessages.TryGetValue(session, out pendingMessages))
                            {
                                pendingMessages = new List<MessageData>();
                                existingSessionMessages.Add(session, pendingMessages);
                            }

                            pendingMessages.Add(data);
                        }
```

in the above snippet of code;
`
List<MessageData> pendingMessages;
`

will remain null, when:

`
if (!existingSessionMessages.TryGetValue(session, out pendingMessages))
`
is not fulfilled. 

Therefore leading to the NullReferenceException on
`
pendingMessages.Add(data);
`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DurableTask.AzureStorage.OrchestrationSessionManager.AddMessageToPendingOrchestration(ControlQueue controlQueue, IEnumerable`1 queueMessages, Guid traceActivityId, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\OrchestrationSessionManager.cs:line 217
   at DurableTask.AzureStorage.OrchestrationSessionManager.DequeueLoop(String partitionId, ControlQueue controlQueue, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\OrchestrationSessionManager.cs:line 166
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by cgillum** [comment]
Hi @chrisw000, it seems to me that if `TryGetValue` returns false, then we will initialize `pendingMessages` and add it to the dictionary for future lookups. If `TryGetValue` returns true, then the assumption is that `pendingMessages` out parameter will not be null (we never add a null value to this dictionary). I'm therefore not sure I understanding how `pendingMessages` can ever be null.

I see that the line number matches this line of code, but I don't see how this null-ref is possible. Did you observe this using the latest version of the nuget package?

**Comment by chrisw000** [comment]
Hi,

I'm referencing Microsoft.Azure.WebJobs.Extensions.Storage 4.0.3 (latest)
that references Microsoft.Azure.Storage.x 11.1.7

I should have said, so far - I've only seen this whilst running the FunctionApp locally.

I can see it happening on a fresh run, after running the command to wipe down history etc.
`func durable delete-task-hub --task-hub-name XXXX`

The code is initiated off a TimerTrigger, and I see it when I present enough data for it to be running for 10-15 mins ( never see it on shorter runs).  Its not consistent when it happens within the processing.

**Comment by cgillum** [comment]
@chrisw000 ah, so you're using this with Azure Functions. I didn't not realize that. What version of **Microsoft.Azure.WebJobs.Extensions.DurableTask** are you using?

**Comment by chrisw000** [comment]
Hi, 
Sorry, I didn't give you the complete picture then...
I've currently got a reference to Microsoft.Azure.WebJobs.Extensions.DurableTask v2.3.0 
Thanks

**Comment by cgillum** [comment]
@chrisw000 thanks. Do you have a simple repro app that demonstrates this problem? Again, just from visual inspection this null-ref doesn't seem possible, but if you're seeing it then I'd love to capture it in a debugger to take a look.

**Comment by chrisw000** [comment]
Hi @cgillum 
Unfortunately its commercial software which I'm not going to be able to share. Do these session values go in/out of the Function History tables? I wondered if it could be that the local storage emulator can't keep up and it looses data?

I'm going away for a couple of days. When I get back on Tuesday I'll try and see if I can reproduce it in simpler app for you.

Thanks.

**Comment by chrisw000** [comment]
Hi @cgillum,

I've not been able to get together a reproduction yet.

When it happens.. there are errors like one the below occur earlier in the run.

I've also noticed that a Sub Orchestrator will re-start a completed Activity. For example, it will complete activity A, then activity B, and then restart activity A again.

Is it possible I'm just trying to do too much against the Azure Storage Emulator ?

An unexpected failure occurred while processing instance '4235615f06e54901b5c51eb7d85d13d1:917': Microsoft.WindowsAzure.Storage.StorageException: Element 4 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String clientRequestId, String account, AzureStorageOrchestrationServiceSettings settings, Func`1 operation) in C:\source\durabletask\src\DurableTask.AzureStorage\TimeoutHandler.cs:line 64
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UploadHistoryBatch(String instanceId, String executionId, TableBatchOperation historyEventBatch, StringBuilder historyEventNamesBuffer, Int32 numberOfTotalEvents, Int32 episodeNumber, Int32 estimatedBatchSizeInBytes, String eTagValue, Boolean isFinalBatch) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1244
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1053
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1005
Request Information
RequestID:94fdb49d-4766-4e50-a993-7495c2e61aff
RequestDate:Fri, 16 Oct 2020 17:53:53 GMT
StatusMessage:4:The specified entity already exists.
ErrorCode:
ErrorMessage:4:The specified entity already exists.
RequestId:94fdb49d-4766-4e50-a993-7495c2e61aff
Time:2020-10-16T17:53:53.4408244Z

**Comment by ChenglongLiu** [comment]
I got a similar issue. In using both **CreateTimer** and **ContinueAsNew** in my Orchestration. The packages' version is

```
<PackageReference Update="Microsoft.Azure.DurableTask.AzureStorage" Version="1.7.7" />
<PackageReference Update="Microsoft.Azure.DurableTask.Core" Version="2.3.0" />
```

Crash message : 
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DurableTask.AzureStorage.OrchestrationSessionManager.AddMessageToPendingOrchestration(ControlQueue controlQueue, IEnumerable`1 queueMessages, Guid traceActivityId, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\OrchestrationSessionManager.cs:line 168
   at DurableTask.AzureStorage.OrchestrationSessionManager.DequeueLoop(String partitionId, ControlQueue controlQueue, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\OrchestrationSessionManager.cs:line 116
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

After an investigation, I confirmed that the line number is not Accurate. The exception is thrown from 

https://github.com/Azure/durabletask/blob/22cd2f5ea9d68028377c6f4bc3cf23705dab2bc5/src/DurableTask.AzureStorage/OrchestrationSessionManager.cs#L170

The ExecutionStartedEvent  in OrchestrationRuntimeState is null. I can reproduce this problem, but it is sporadic. When it occurred, the System.Diagnostics.StackTrace() as below

```
   at DurableTask.Core.OrchestrationRuntimeState.get_CreatedTime()
   at DurableTask.AzureStorage.OrchestrationSessionManager.AddMessageToPendingOrchestration(ControlQueue controlQueue, IEnumerable`1 queueMessages, Guid traceActivityId, CancellationToken cancellationToken)
   at DurableTask.AzureStorage.OrchestrationSessionManager.DequeueLoop(String partitionId, ControlQueue controlQueue, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at DurableTask.AzureStorage.Messaging.ControlQueue.GetMessagesAsync(CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String clientRequestId, String account, String taskHub, Func`1 operation)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by cgillum** [comment]
Ah, that's interesting. I think this means the target instance doesn't exist because it's state was removed due to ContinueAsNew. It seems to be a race condition that we're not handling properly. We will need to add a check for this condition. I think in this case the correct behavior is to discard the message.
