### ISSUE TITLE
Invalid characters in InstanceId

### ISSUE THREAD

**Issue by saguiitay** [Azure/durabletask#518]
Apparently, InstanceId is restricted to URL-supported characters. This is not documented anywhere. After setting an InstanceId to a value that contains a `/`, I got an error. The worrysome part is the error was thrown quite deeply in the stack (from Durable.Storage - see stack trace below).

I'm not 100% sure about the following part, but I think that this also result in the orchestration being registered and partially executed anyway...

```csharp
The remote server returned an error: (400) Bad Request. (wrapped in an AggregateException with message: One or more errors occurred.)
System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.<SetNewExecutionAsync>d__55.MoveNext() in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 883
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<CreateTaskOrchestrationAsync>d__103.MoveNext() in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1644
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskHubClient.<InternalCreateOrchestrationInstanceWithRaisedEventAsync>d__27.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskHubClient.cs:line 616
```

**Comment by ConnorMcMahon** [comment]
This _should_ be fixed in our next release that is coming out early next week (see #505).
