### ISSUE TITLE
TaskOrchestrationDispatcher: Failed to fetch a work-item

### ISSUE THREAD

**Issue by mlankamp** [Azure/durabletask#520]
When I create a TaskHubWorker with a ServiceBusOrchestrationService, I see the following errors in my logs:
```
TaskOrchestrationDispatcher-e531d2a92f314296a4e7408333df3278-0: Failed to fetch a work-item: Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: The operation did not complete within the allotted timeout of 00:00:29.9790000. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:54091dd1-6c47-463d-a171-b510613e030a_B4, SystemTracker:********:Queue:taskhub/orchestrator, Timestamp:2021-03-15T21:34:56 TrackingId:3ae635737d02479c9e1944fedc51af50_G1, SystemTracker:gateway7, Timestamp:2021-03-15T21:34:56
         at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
         at DurableTask.ServiceBus.Common.Abstraction.SessionClient.AcceptMessageSessionAsync(TimeSpan operationTimeout) in C:\source\durabletask\src\DurableTask.ServiceBus\Common\Abstraction\ServiceBusAbstraction.cs:line 946
         at DurableTask.ServiceBus.ServiceBusOrchestrationService.LockNextTaskOrchestrationWorkItemAsync(TimeSpan receiveTimeout, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 533
         at DurableTask.Core.WorkItemDispatcher`1.DispatchAsync(WorkItemDispatcherContext context) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 262
Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: The operation did not complete within the allotted timeout of 00:00:29.9790000. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:54091dd1-6c47-463d-a171-b510613e030a_B4, SystemTracker:********:Queue:taskhub/orchestrator, Timestamp:2021-03-15T21:34:56 TrackingId:3ae635737d02479c9e1944fedc51af50_G1, SystemTracker:gateway7, Timestamp:2021-03-15T21:34:56
   at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
   at DurableTask.ServiceBus.Common.Abstraction.SessionClient.AcceptMessageSessionAsync(TimeSpan operationTimeout) in C:\source\durabletask\src\DurableTask.ServiceBus\Common\Abstraction\ServiceBusAbstraction.cs:line 946
   at DurableTask.ServiceBus.ServiceBusOrchestrationService.LockNextTaskOrchestrationWorkItemAsync(TimeSpan receiveTimeout, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.ServiceBus\ServiceBusOrchestrationService.cs:line 533
   at DurableTask.Core.WorkItemDispatcher`1.DispatchAsync(WorkItemDispatcherContext context) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 262
dbug: DurableTask.Core[23]
```

**Comment by cgillum** [comment]
What is the impact of this issue? Is something broken or is this just noise in your logs? Also, can you share a snippet of the code that can reproduce the problem?

**Comment by mlankamp** [comment]
I don't know if it's a issue, doesn't seem te be. I'm able to reproduce the error with the following code:

```c#
var loggerFactory = LoggerFactory.Create(builder => {
    builder.SetMinimumLevel(LogLevel.Trace)
        .AddDebug()
        .AddConsole();
});

string serviceBusConnectionString = "-- connectionstring --";
string storageConnectionString = "-- connectionstring --";
string taskHubName = "taskhubname";

IOrchestrationServiceInstanceStore instanceStore = new AzureTableInstanceStore(taskHubName, storageConnectionString);

var orchestrationServiceAndClient = new ServiceBusOrchestrationService(serviceBusConnectionString, taskHubName, instanceStore, null, null);

var taskHub = new TaskHubWorker(orchestrationServiceAndClient, loggerFactory);

orchestrationServiceAndClient.CreateIfNotExistsAsync().Wait();

taskHub.StartAsync().Wait();

Console.WriteLine("Press any key to quit.");
Console.ReadLine();
}
```

My nuget packages:
```
<PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="2.5.1" />
<PackageReference Include="Microsoft.Azure.DurableTask.ServiceBus" Version="2.4.0" />
<PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.2" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.13" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.13" />
```

After I start my application, I have to wait for about 1 minute and then the error starts.

**Comment by cgillum** [comment]
@mlankamp thanks. I suspect this may be a logging issue in the `ServiceBusOrchestrationService` where routine exception messages are being logged when they shouldn't be. The fix is probably to add some exception handling in the `AcceptMessageSessionAsync` methods and returning null since this is (I believe) a non-error exception.

**Comment by mlankamp** [comment]
@cgillum thanks. I've created a PR to fix the excessive logging.
