### ISSUE TITLE
[Bug] AzureStorage queue can become stuck on corrupt message.

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#553]
**Issue**

DurableTask.AzureStorage does not have a dead-letter equivalent like ServiceBus does. This means that a corrupt message in the queue can effectively block a worker permanently, until that message is manually removed. If you somehow get a message in a control queue which DTFx.AzureStorage can not deserialize without throwing, the worker will get stuck on that message. Repeatedly de-queueing it and throwing, never progressing onto the next message in the queue. In ServiceBus this is handled by eventually dead-lettering that message, removing it from the queue after so many failed deliveries.

**Request**

Implement a dead-letter equivalent to ServiceBus, where if the same message fails to be processed some number of times. Ideally there would be some way to store and flag the failed message for review later on.

**Comment by cgillum** [comment]
Do you think orchestrations should continue processing other messages or do you think the orchestration should go into a "suspended" state where we store/save all messages somewhere and wait for it to be unsuspended before letting anything continue?

**Comment by jviau** [comment]
That would depend on the how Azure Queue's behave I guess - I am not super familiar with it. DTFx _should_ continue eventually at the very least. My guess is there are two options:

1) Keep processing the same message with a backoff in between deserialization failures. DTFx will eventually give up on the message and abandon it and continue onto the next messages.
   - How long will DTFx stay blocked on that message?
   - How will DTFx track that a message has failed so many times? I think AzureStorage API has a delivery count on it, but will that delivery count be impacted by other transient failures?
1) On each failure, put the message further back in the queue and process some other messages before getting back to the failure.
   - Does DTFx have ordering requirements on the messages in the queue?
   - Does AzureStorage queues even have the ability to move a messages position in the queue? (Can also remove it entirely and re-add it at the end I guess).

I'll admit - this is a hard problem and I am not sure what the optimal solution is. All I know, is it doesn't make sense for the **entire** worker to be blocked when there is a single corrupted message in the control queue. Abandoning the corrupt message will also lead to any dependent orchestrations waiting indefinitely - hopefully there is a way to identify what orchestration or activity that message was for, and to go fail it, so all of its dependencies will also fail or have a chance to retry. I think orphaned orchestrations is a problem generally in DTFx though (simply yield within the orchestration and have no more open tasks or events coming to the orchestration - that orchestration is now orphaned) so this solution could also cover the other scenarios for that.

**Comment by sebastianburckhardt** [comment]
Just to be clear: by "worker" you mean orchestration?  And by "queue" you mean events sent to the orchestration?

Our runtime-internal workers and queues are already designed so to keep working independently of any errors occurring at the application level, within orchestrations. For example, deserialization errors in one orchestration should never block progress of other orchestrations. 

Just out of curiosity, is this something you observed? What were the circumstances that caused a corrupt message to be inserted into the queue? And what were the effects for your application?

**Comment by jviau** [comment]
Worker I mean the `TaskHubWorker` and queue is the Azure storage queue DurableTask.AzureStorage uses.

And yes, this is something I observed. The exception was thrown in this stack:

> EventName: MessageFailure
EventId: 114
An error occurred while processing messages on mljobs-control-02: Newtonsoft.Json.JsonSerializationException: Could not create an instance of type DurableTask.Core.History.HistoryEvent.
.
.
.
at DurableTask.AzureStorage.MessageManager.DeserializeQueueMessageAsync(CloudQueueMessage queueMessage, String queueName) in C:\source\durabletask\src\DurableTask.AzureStorage\MessageManager.cs:line 162
at DurableTask.AzureStorage.Messaging.WorkItemQueue.GetMessageAsync(CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\Messaging\WorkItemQueue.cs:line 66

We know what caused the exception - switching how things were serialized/deserialized in DTFx, which made all existing messages in the queue break. The assumption was those messages would be drained out as they failed and DTFx would move on, but instead we found DTFx made zero progress at all. No newly started orchestrations would be ran at all (they would have been in the correct serialization format). Instead, our logs just filled with these errors from DTFx. Even after leaving it overnight, no progress was made on the 'good' orchestrations.

Luckily this all happened in our test environment.
