### ISSUE TITLE
ArgumentOutOfRangeException at DurableTask.AzureStorage.Messaging.TaskHubQueue.AddMessageAsync

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#571]
I am looking over our telemetry, and I see that DTFx is logging a non trivial amount of these exceptions:

```
  System.ArgumentOutOfRangeException: The argument 'initialVisibilityDelay' is larger than maximum of '6.23:59:59' (Parameter 'initialVisibilityDelay')
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertInBounds[T](String paramName, T val, T min, T max)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext)
   at DurableTask.AzureStorage.Messaging.TaskHubQueue.AddMessageAsync(TaskMessage taskMessage, OrchestrationInstance sourceInstance, SessionBase session) in C:\source\durabletask\src\DurableTask.AzureStorage\Messaging\TaskHubQueue.cs:line 165
   at DurableTask.AzureStorage.Utils.InvokeThrottledAction[T](T item, Func`2 action, SemaphoreSlim semaphore) in C:\source\durabletask\src\DurableTask.AzureStorage\Utils.cs:line 82
   at DurableTask.AzureStorage.Utils.ParallelForEachAsync[T](IList`1 items, Int32 maxConcurrency, Func`2 action) in C:\source\durabletask\src\DurableTask.AzureStorage\Utils.cs:line 67
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CommitOutboundQueueMessages(OrchestrationSession session, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1317
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1161
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 561
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 191
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 459

Backing off for 10 seconds until 5 successful operations
```

I am unable to repro it myself, or really understand the impact of these exceptions. Are they red herrings? Should I ignore them? Or are they worth further investigation?

**Comment by cgillum** [comment]
@jviau What version of the DurableTask.AzureStorage nuget package are you using? I remember fixing a similar issue a while back.

**Comment by jviau** [comment]
1.8.5 - didn't notice there was newer versions! I'll update to 1.8.7 and see if this persists.

**Comment by cgillum** [comment]
It looks like the fix I was referring to is for a different code path: https://github.com/Azure/durabletask/commit/5fa90f0bcd0a52590b8cbda503979ba5d08b745e (abandoning messages). I'm just now realizing that your case is different - it looks like your orchestration is creating durable timers that exceed the 7 day limit. There's probably some missing validation for this which we have for Durable Functions but not for DTFx.

This is not a red-herring. This would either cause orchestrations to fail or to get stuck. It looks like it also causes the DTFx dispatcher to start throttling itself, which will reduce overall throughput pretty dramatically.

**Comment by jviau** [comment]
Got it! Yeah, I think we might have something that is delaying for greater than 7 days. I suppose it would be easy to split that delay up into smaller calls.

**Comment by jviau** [comment]
Okay, I think this was a problem on our end. I'll close this issue for now. Thank you for the help!
