### ISSUE TITLE
DurableTask should be resilient to Azure Blob storage hangs

### ISSUE THREAD

**Issue by Robulane** [Azure/durabletask#614]
On our production servers, we have caught an issue in Durable Task framework. 

Main issue (how the issue manifests): the call to StopAsync method on TaskHubWorker hangs forever.

I did some deep investigations to the logs and found the original cause. Some facts from logs:
1. The awaiting of "takerTask" in LeaseCollectionBalancer.StopAsync method hangs. This happens because:
2. DownloadLeaseBlob method in BlobLeaseManager.cs hangs.

The latter fact I understood from the logs. We have a logging for all outcoming http requests. During the first 2 days after the service start, every 5 seconds we had the following logs:

- 4 GET requests (to download blob)
- 4 HEAD requests (for fetch attributes)

At some point, the logging stopped (while service was still active for a few days). The last logs contains:

- 4 GET requests
- 3 HEAD requests

![image](https://user-images.githubusercontent.com/55888168/134957638-3982651f-077a-4753-b2e0-3ad852a12afd.png)

All the evidence shows that the hang happens in Azure Blob client. DurableTask SDK should be resilient to it. E.g. it should have a default timeout for all blob operations.

**Comment by cgillum** [comment]
Which version of the Microsoft.Azure.DurableTask.AzureStorage nuget package are you using? The latest v1.9.x version should be resilient to hanging Azure Blob operations.

/cc @amdeel

**Comment by Robulane** [comment]
We are using 1.8.5. Do you have a link to the commit that makes it resilient?

**Comment by ConnorMcMahon** [comment]
@Robulane,

So this is a bug with the version of the Storage SDK that happens regardless of setting a timeout. We have a wrapper function that attempts retries and eventually recycles the app after enough retries, but we applied this wrapper function on a case-by-case basis.

After [this commit](https://github.com/Azure/durabletask/commit/0b003c9493d6d657921bf5bf86126ac8911deeb3#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26), all blob and queue operations go through this code path.

**Comment by tom-configo** [comment]
@ConnorMcMahon Is this a known bug with the Storage SDK? Is there a corresponding issue? We are seeing this very regularly, even when testing with a single orchestration instance with a non-parallel sequence of activity functions. Our activity functions are quite long-running and CPU-intensive. The FailFast and restart happens several times every time we run this orchestration, and the orchestration rarely runs to completion (either because it fails, or because it just spends hours restarting repeatedly and we eventually have to kill it). An example from the app event log:

```
Application: w3wp.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: The operation 'Queue UpdateMessage' with id 'b6df370c-d60c-4e4c-a1ba-2ef595df52f5' did not complete in '00:02:00'. Hit maximum number (5) of timeouts. Terminating the process to mitigate potential deadlock.
```

**Comment by davidmrdavid** [comment]
@tom-configo: just a heads up that Connor is no longer working with the team, so he won't be responding to this thread.

From Connor's last comment, it would appear this is a known bug with the Storage SDK. Does @amdeel or @cgillum have more context?

**Comment by dgiagio** [comment]
I'm hitting a similar problem many times. We're running thousands of orchestrations in parallel:

The operation 'Queue AddMessage' with id '684cb8d0-f02d-418c-a3e5-0b99ce5a901c' did not complete in '00:02:00'. Hit maximum number (5) of timeouts. Terminating the process to mitigate potential deadlock.

**Comment by ltouro** [comment]
We started to receive this errors reguarly:

2023-11-16T19:41:35.336283605Z Process terminated. The operation 'Queue AddMessage' with id 'd73f76b3-4981-4d21-bf52-c3309ca348d0' did not complete in '00:02:00'. Hit maximum number (5) of timeouts. Terminating the process to mitigate potential deadlock.
2023-11-16T19:41:35.336316106Z    at System.Environment.FailFast(System.String)
2023-11-16T19:41:35.336322306Z    at DurableTask.AzureStorage.TimeoutHandler+<>c.<.cctor>b__7_0(System.String)
2023-11-16T19:41:35.336326406Z    at DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d__6`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
2023-11-16T19:41:35.336329306Z    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2023-11-16T19:41:35.336336206Z    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d__6`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], DurableTask.AzureStorage, Version=1.12.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd]].MoveNext(System.Threading.Thread)
2023-11-16T19:41:35.336351506Z    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
2023-11-16T19:41:35.336356006Z    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2023-11-16T19:41:35.336361207Z    at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
2023-11-16T19:41:35.336365607Z    at System.Threading.Tasks.Task+TwoTaskWhenAnyPromise`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(System.Threading.Tasks.Task)
2023-11-16T19:41:35.336368307Z    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2023-11-16T19:41:35.336377407Z    at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(Boolean)
2023-11-16T19:41:35.336385707Z    at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
2023-11-16T19:41:35.336390607Z    at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessInnerTask(System.Threading.Tasks.Task)
2023-11-16T19:41:35.336402307Z    at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessCompletedOuterTask(System.Threading.Tasks.Task)
2023-11-16T19:41:35.336406807Z    at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InvokeCore(System.Threading.Tasks.Task)
2023-11-16T19:41:35.336530609Z    at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(System.Threading.Tasks.Task)
2023-11-16T19:41:35.336554710Z    at System.Threading.Tasks.Task.RunContinuations(System.Object)
2023-11-16T19:41:35.336560310Z    at System.Threading.Tasks.Task.FinishSlow(Boolean)
2023-11-16T19:41:35.336564310Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
2023-11-16T19:41:35.336567810Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-11-16T19:41:35.336571310Z    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

**Comment by cgillum** [comment]
By chance are you running your app in a separate data center than the one where the Azure Storage account is? From what we've seen, that tends to increase the likelihood of running into these deadlocks. Basically, it's believed to be more common when there's higher network latency or when the network connectivity is less stable.

Note that we expect this will be completely fixed once we release the DurableTask.AzureStorage v2, which uses the most up-to-date generation of the Azure Storage SDKs. The deadlock bug should be completely gone in those versions.

**Comment by ltouro** [comment]
Just checked and, for my surprise, you are correct. The storage account is eastus while the app is Brazil South.

Do you thing upgrading Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.13.0 can help mitigate that?

**Comment by cgillum** [comment]
Thanks for confirming!

Upgrading `Microsoft.Azure.WebJobs.Extensions.DurableTask` to 2.13.0 unfortunately won't help since it still depends on `DurableTask.AzureStorage` v1.x, which uses the deprecated Azure Storage SDK that has the deadlock problems.

`DurableTask.AzureStorage` v2 should be available soon, along with `Microsoft.Azure.WebJobs.Extensions.DurableTask` v3. I believe @nytian is just doing some final validations before doing the preview release.

**Comment by ltouro** [comment]
Thanks for helping so promptly! We will migrate to the same datacenter in the meantime.
