### ISSUE TITLE
Failed to deserialize exception from TaskActivity

### ISSUE THREAD

**Issue by RDavis3000** [Azure/durabletask#664]
Hi,

Hopefully a simple one and hopefully this is the right place for it.

I'm getting a "Failed to deserialize exception from TaskActivity" exception in the stack trace when my activity function causes a vanilla unhandled SqlException. The stack-trace came from the Portal->Application Insights->Failures blade and was thrown by the orchestrator after bubbling up from the Activity.

Looks like Newtonsoft is choking on a Guid:

--> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.Guid'.
   at System.Data.SqlClient.SqlException..ctor(SerializationInfo si, StreamingContext sc)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at DurableTask.Core.Serializing.DataConverter.Deserialize[T](String data) in C:\source\durabletask\src\DurableTask.Core\Serializing\DataConverter.cs:line 54
   at DurableTask.Core.Common.Utils.RetrieveCause(String details, DataConverter converter) in C:\source\durabletask\src\DurableTask.Core\Common\Utils.cs:line 401
   --- End of inner exception stack trace ---

FULL STACK TRACE

758130bb46d6415f84ec822c28ca0626: Function 'XXXXDocSettingsDBStorageOrchestrator (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The orchestrator function 'XXXXDocSettingsDBStorageStatusSubOrchestrator' failed: "The activity function 'XXXXDocSettingsMapDocSettingsToStatusActivity' failed: "Failed to deserialize exception from TaskActivity: {"$type":"System.Data.SqlClient.SqlException, System.Data.SqlClient","ClassName":"System.Data.SqlClient.SqlException","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.\r\nThe statement has been terminated.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib","HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"12.00.2255","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"547","HelpLink.BaseHelpUrl":"https://go.microsoft.com/fwlink","HelpLink.LinkId":"20476","OriginalClientConnectionId":"d2fb5771-ef87-4509-a0df-bdf45f6952ce","RoutingDestination":"c1a7a5f77765.tr32.australiaeast1-a.worker.database.windows.net,11037","SqlError 1":"System.Data.SqlClient.SqlError: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.","SqlError 2":"System.Data.SqlClient.SqlError: The statement has been terminated."},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryMultipleAsync(IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1013\r\n   at SqlServerAdapter.InsertAsync(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in /_/Dapper.Contrib/SqlMapperExtensions.Async.cs:line 380\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.InsertDocSettingsStatusMapDTOAsync(DocSettingStatusMapDTO value) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 244\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.MapDocSettingsToStatusAsync(DocSettingStatusMapDTO docSettingStatusMapDTO) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 228\r\n   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsMapDocSettingsToStatusActivity(DocSettingStatusMapDTO docSettingStatusMapDTO, ILogger log) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.FunctionApp\\IngestionFunctions\\XXXX\\XXXXDocSettingDBStorageFunction.cs:line 274\r\n   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs:line 20\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 572\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 518\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 296","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232060,"Source":"Core .Net SqlClient Data Provider","WatsonBuckets":null,"Errors":null,"ClientConnectionId":"602b9301-e377-4eaa-b3e9-5cd85f206ff8"}". See the function execution logs for additional details.". See the function execution logs for additional details.
 ---> Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'XXXXDocSettingsMapDocSettingsToStatusActivity' failed: "Failed to deserialize exception from TaskActivity: {"$type":"System.Data.SqlClient.SqlException, System.Data.SqlClient","ClassName":"System.Data.SqlClient.SqlException","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.\r\nThe statement has been terminated.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib","HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"12.00.2255","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"547","HelpLink.BaseHelpUrl":"https://go.microsoft.com/fwlink","HelpLink.LinkId":"20476","OriginalClientConnectionId":"d2fb5771-ef87-4509-a0df-bdf45f6952ce","RoutingDestination":"c1a7a5f77765.tr32.australiaeast1-a.worker.database.windows.net,11037","SqlError 1":"System.Data.SqlClient.SqlError: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.","SqlError 2":"System.Data.SqlClient.SqlError: The statement has been terminated."},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryMultipleAsync(IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1013\r\n   at SqlServerAdapter.InsertAsync(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in /_/Dapper.Contrib/SqlMapperExtensions.Async.cs:line 380\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.InsertDocSettingsStatusMapDTOAsync(DocSettingStatusMapDTO value) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 244\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.MapDocSettingsToStatusAsync(DocSettingStatusMapDTO docSettingStatusMapDTO) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 228\r\n   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsMapDocSettingsToStatusActivity(DocSettingStatusMapDTO docSettingStatusMapDTO, ILogger log) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.FunctionApp\\IngestionFunctions\\XXXX\\XXXXDocSettingDBStorageFunction.cs:line 274\r\n   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs:line 20\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 572\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 518\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 296","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232060,"Source":"Core .Net SqlClient Data Provider","WatsonBuckets":null,"Errors":null,"ClientConnectionId":"602b9301-e377-4eaa-b3e9-5cd85f206ff8"}". See the function execution logs for additional details.
 ---> DurableTask.Core.Exceptions.TaskFailedExceptionDeserializationException: Failed to deserialize exception from TaskActivity: {"$type":"System.Data.SqlClient.SqlException, System.Data.SqlClient","ClassName":"System.Data.SqlClient.SqlException","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.\r\nThe statement has been terminated.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib","HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"12.00.2255","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"547","HelpLink.BaseHelpUrl":"https://go.microsoft.com/fwlink","HelpLink.LinkId":"20476","OriginalClientConnectionId":"d2fb5771-ef87-4509-a0df-bdf45f6952ce","RoutingDestination":"c1a7a5f77765.tr32.australiaeast1-a.worker.database.windows.net,11037","SqlError 1":"System.Data.SqlClient.SqlError: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_DocSettingsStatusesMap_DocSettings\". The conflict occurred in database \"db-u-lxr-aue-crs-tbforms\", table \"XXXX.DocSettings\", column 'Id'.","SqlError 2":"System.Data.SqlClient.SqlError: The statement has been terminated."},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryMultipleAsync(IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1013\r\n   at SqlServerAdapter.InsertAsync(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in /_/Dapper.Contrib/SqlMapperExtensions.Async.cs:line 380\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.InsertDocSettingsStatusMapDTOAsync(DocSettingStatusMapDTO value) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 244\r\n   at XXOrgNameXX.XXXX.Repo.XXXXRepository.MapDocSettingsToStatusAsync(DocSettingStatusMapDTO docSettingStatusMapDTO) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.XXXX\\Repo\\XXXXRepository.cs:line 228\r\n   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsMapDocSettingsToStatusActivity(DocSettingStatusMapDTO docSettingStatusMapDTO, ILogger log) in C:\\GITPATHXXOrgNameXX\\XXOrgNameXX.FunctionApp\\IngestionFunctions\\XXXX\\XXXXDocSettingDBStorageFunction.cs:line 274\r\n   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs:line 20\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 572\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 518\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 296","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232060,"Source":"Core .Net SqlClient Data Provider","WatsonBuckets":null,"Errors":null,"ClientConnectionId":"602b9301-e377-4eaa-b3e9-5cd85f206ff8"}
 ---> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.Guid'.
   at System.Data.SqlClient.SqlException..ctor(SerializationInfo si, StreamingContext sc)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at DurableTask.Core.Serializing.DataConverter.Deserialize[T](String data) in C:\source\durabletask\src\DurableTask.Core\Serializing\DataConverter.cs:line 54
   at DurableTask.Core.Common.Utils.RetrieveCause(String details, DataConverter converter) in C:\source\durabletask\src\DurableTask.Core\Common\Utils.cs:line 401
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 710
   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsDBStorageStatusSubOrchestrator(IDurableOrchestrationContext context) in C:\GITPATH\XXOrgNameXX\XXOrgNameXX.FunctionApp\IngestionFunctions\XXXX\XXXXDocSettingDBStorageFunction.cs:line 195
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 720
   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsDBStorageOrchestrator(IDurableOrchestrationContext context, ILogger log) in C:\GITPATH\XXOrgNameXX\XXOrgNameXX.FunctionApp\IngestionFunctions\XXXX\XXXXDocSettingDBStorageFunction.cs:line 148
   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsDBStorageOrchestrator(IDurableOrchestrationContext context, ILogger log) in C:\GITPATH\XXOrgNameXX\XXOrgNameXX.FunctionApp\IngestionFunctions\XXXX\XXXXDocSettingDBStorageFunction.cs:line 171
   at XXOrgNameXX.FunctionApp.IngestionFunctions.XXXX.XXXXDocSettingDBStorageFunction.XXXXDocSettingsDBStorageOrchestrator(IDurableOrchestrationContext context, ILogger log) in C:\GITPATH\XXOrgNameXX\XXOrgNameXX.FunctionApp\IngestionFunctions\XXXX\XXXXDocSettingDBStorageFunction.cs:line 178
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: fadlxraueingestion. AppName: fa-d-lxr-aue-ingestion. SlotName: Production. ExtensionVersion: 2.5.1. SequenceNumber: 129150. TaskEventId: -1

**Comment by cgillum** [comment]
Unfortunately, the built-in exception serialization logic in the Durable Task Framework doesn't handle a variety of exception types very well. I see that you're using Durable Functions, so my recommendation is to try and use the extensibility offered there to inject your own serialization logic to work around these kinds of issues: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp#customizing-serialization-with-dependency-injection
