### ISSUE TITLE
Receiving "ParentInstanceID" error while executing the method "WaitForOrchestrationAsync"

### ISSUE THREAD

**Issue by DanielGigante12345** [Azure/durabletask#739]
After upgrading to the "Microsoft.DurableTask.SqlServer (1.0.0-rc)" and executing 25000 x in parallel the method "WaitForOrchestrationAsync" I receive:

at Microsoft.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
at Microsoft.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
at DurableTask.SqlServer.SqlUtils.GetParentInstanceId(DbDataReader reader)
at DurableTask.SqlServer.SqlUtils.GetOrchestrationState(DbDataReader reader)
at DurableTask.SqlServer.SqlOrchestrationService.<GetOrchestrationStateAsync>d__30.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at DurableTask.SqlServer.SqlOrchestrationService.<**WaitForOrchestrationAsync**>d__28.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at liebherr.workflow.durable.Orchestrations.WkfRequestHolidays.WkfRequestHolidaysOrchestrator.<WkfRequestHolidayCreateOrchestrator>d__30.MoveNext() in C:\Archive\Sources_NET\LMB.WFE.Prototype\liebherr.workflow.durable\Orchestrations\WkfRequestHolidays\WkfRequestHolidaysOrchestrator.cs:line 67

This is happening with SQL Server 2016. 
No issue detected with SQL Server 2019.
No issue detected with the "0.11.1-beta" version neither on 2016 nor on 2019.

The method raising the error:

![image](https://user-images.githubusercontent.com/101813547/171209003-4e942a76-85bc-43c5-b5a6-a81f267fd9cc.png)

![image](https://user-images.githubusercontent.com/101813547/171207965-e58e71bd-b8a7-4af7-ae9d-44f2b766d0b3.png)

![image](https://user-images.githubusercontent.com/101813547/171207925-0ab299c4-6824-4de0-858e-5f85a8c25151.png)

**Comment by DanielGigante12345** [comment]
As you suggested, I deleted and then recreated the whole database through the "CreateIfNotExistsAsync" method and so far there are now no more errors.
Thanks.

Just a question though: when using the "CreateIfNotExistsAsync" method does that mean that if there are new schemas the procedure will delete the content of the durable tables prior to recreating the schemas ?

**Comment by cgillum** [comment]
> Just a question though: when using the "CreateIfNotExistsAsync" method does that mean that if there are new schemas the procedure will delete the content of the durable tables prior to recreating the schemas?

This method should update the stored procedures but won't actually delete anything.

Note that in the future, starting with the v1.0.0 (GA) release, updates to the SQL backend will take care of automatically migrating schema so that you'll never need to recreate the database.

**Comment by cgillum** [comment]
I think this issue should be good to close.

@DanielGigante12345 for future reference, the best place to open issues when using the MSSQL backend is https://github.com/microsoft/durabletask-mssql. Let us know there if you have any other questions or feedback. Thanks!
