### ISSUE TITLE
Support method overloading in AddTaskActivitiesFromX

### ISSUE THREAD

**Issue by papigers** [Azure/durabletask#795]
When trying to call AddTaskActivitiesFromInterface with an interface that has multiple signatures of the same mehtod name we encounter this exception:
```
Duplicate entry detected: IResourceManagerUtils.GetResourcesAsync 
System.InvalidOperationException: Duplicate entry detected: IResourceManagerUtils.GetResourcesAsync 
   at DurableTask.Core.NameVersionObjectManager`1.Add(ObjectCreator`1 creator) in /_/src/DurableTask.Core/NameVersionObjectManager.cs:line 31
   at DurableTask.Core.TaskHubWorker.AddTaskActivitiesFromInterface(Type interface, Object activities, Boolean useFullyQualifiedMethodNames) in /_/src/DurableTask.Core/TaskHubWorker.cs:line 393
```

The cause is pretty self-explanatory, since only the method names is used to describe the activity, and the other components of the method signature are ignored, a conflict is crated.
Perhaps the version could be utilized to correlate each overload with a dedicated activity? Though I'm not sure how backward-compatibility is preserved in that way

**Comment by saguiitay** [comment]
@cgillum, @jviau can someone take a look at this?

**Comment by cgillum** [comment]
I feel like there’s a lot of hidden complexity in a feature like this, backwards compatibility being one of them. I would prefer a model where interface methods are more explicitly mapped to activity names, perhaps using attributes. Thoughts on that as an alternative approach?

**Comment by saguiitay** [comment]
Using Attributes is definetely a viable approach for us (but I'd rather using some generic attribute, and not have DurableTask code sprinkled all over my interfaces)

**Comment by papigers** [comment]
@cgillum @saguiitay Perhaps [DisplayNameAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.displaynameattribute?view=net-7.0)?
I'd be happy to submit a PR for this issue, we're currently having a lot of dummy task activities that just call an instance method, for that reason alone.

**Comment by jviau** [comment]
Could we allow for a simple callback to be provided on `AddActivitiesFromInterface` to resolve an activity name from `MethodInfo`? So `AddActivitiesFromInterface(Type interfaceType, Func<MethodInfo, string> nameResolver)` - can play with that contract a bit to find the right solution, but it is start.
