### ISSUE TITLE
Doesn't work with Service Bus Premium Tier

### ISSUE THREAD

**Issue by mzahor** [Azure/durabletask#80]
We recently migrated to Service Bus Premium on Azure and for some reason Durable Task doesn't work with it. It works fine if I switch it back to basic subscription though.
I've checked out the source code and debugged into the framework itself.
Looks like we're getting `TimeoutException` while fetching work item. Exception details:

```
System.TimeoutException occurred
  HResult=0x80131505
  Message=A timeout has occurred during the operation. 3ce0641d-9948-41a5-9d33-462840602d83_G2
  Source=Microsoft.ServiceBus
  StackTrace:
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpQueueClient.OnEndAcceptMessageSession(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.QueueClient.RetryAcceptMessageSessionAsyncResult.<>c.<GetAsyncSteps>b__12_1(RetryAcceptMessageSessionAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.QueueClient.RetryAcceptMessageSessionAsyncResult.End(IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.QueueClient.EndAcceptMessageSession(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DurableTask.TrackingDispatcher.<OnFetchWorkItem>d__15.MoveNext() in C:\src\durabletask\Framework\TrackingDispatcher.cs:line 79

Inner Exception 1:
FaultException`1: A timeout has occurred during the operation. 3ce0641d-9948-41a5-9d33-462840602d83_G2
```

Also we're getting two other types of exceptions:

```
System.TimeoutException occurred
  HResult=0x80131505
  Message=The request operation did not complete within the allotted timeout of 00:01:09.9994990. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:c8bf9166-a324-455e-9b71-b9bfbeaa3d14, Timestamp:3/22/2017 1:16:30 PM
  Source=mscorlib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<>c.<GetAsyncSteps>b__18_3(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndSend(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageSender.OnSend(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at DurableTask.TaskOrchestrationDispatcher.<OnProcessWorkItem>b__31_4(MessageContainer m) in C:\src\durabletask\Framework\TaskOrchestrationDispatcher.cs:line 428
```
and

```
Microsoft.ServiceBus.Messaging.SessionLockLostException occurred
  HResult=0x80131500
  Message=Channel:uuid:f0f18c6e-bee1-43bf-878f-349069c0a19d;id=6;Link:pe_bee0af0ebdf6486592fdaf2ac53d7e75_87912 TrackingId:6ad89372-54b7-4d8e-b939-ddf405683531_G3_B8, SystemTracker:net.tcp://10.0.0.36:20008/220/Runtime, Timestamp:3/22/2017 1:16:46 PM
  Source=Microsoft.ServiceBus
  StackTrace:
   at Microsoft.ServiceBus.Common.ExceptionExtensions.ThrowException(Exception exception)
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndAbandon(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DurableTask.TaskOrchestrationDispatcher.<AbortWorkItem>d__44.MoveNext() in C:\src\durabletask\Framework\TaskOrchestrationDispatcher.cs:line 863

Inner Exception 1:
FaultException`1: Channel:uuid:f0f18c6e-bee1-43bf-878f-349069c0a19d;id=6;Link:pe_bee0af0ebdf6486592fdaf2ac53d7e75_87912 TrackingId:6ad89372-54b7-4d8e-b939-ddf405683531_G3_B8, SystemTracker:net.tcp://10.0.0.36:20008/220/Runtime, Timestamp:3/22/2017 1:16:46 PM
```

Can I provide you with some other details which may help to resolve the problem?

**Comment by simonporter** [comment]
Premium Service Bus is partitioned by default which causes issues when sending batches, transactions and transfer queues. The bulk of changes needed to fix this are in this branch but there is at least one more issue that needs to be resolved for this:
https://github.com/Azure/durabletask/tree/siport/vnext/partitions
Note this is off the vnext branch which has significant changes but is production ready.

**Comment by mzahor** [comment]
Thanks a lot for your response, I'll take a look.

**Comment by mzahor** [comment]
Two questions:
1. Which exactly issue needs to be resolved (if it's production ready, I suppose issue is not critical)?
2. When can we expect it to be released on NuGet?

**Comment by simonporter** [comment]
I meant that the vnext branch is production ready not the partitioning work specifically, that does have one issue that I believe is critical (with ContinueAsNew IIRC).
This vnext branch is being used as a submodule currently, no fixed release date in nuget yet.

**Comment by mzahor** [comment]
Ok, thanks.
