### ISSUE TITLE
Weird error showing in console - TaskActivityDispatcher...System.ArgumentNullException: Value cannot be null. (Parameter 'executor')

### ISSUE THREAD

**Issue by PeterAnaniaHC** [Azure/durabletask#803]
Team,

Really sorry to bother you, but I'm getting this for days and I'm no closer to figuring out why.

First, it doesn't affect the application at all; everything works fine.
Second, I delete everything in my storage, so none of these items are actually there.
Third, I'm not running anything when I get these errors, they just start appearing in my console log as soon as I start the application.

So you can see why it's a bit nerve racking.

Here's one example error (but I get lot's of them)

[2022-10-10T19:25:24.029Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim..ctor(DurableTaskExtension config, ITriggeredFunctionExecutor executor, IApplicationLifetimeWrapper hostServiceLifetime, String activityName) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 37
[2022-10-10T19:25:24.034Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.DurableTask.Core.INameVersionObjectManager<DurableTask.Core.TaskActivity>.GetObject(String name, String version) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\DurableTaskExtension.cs:line 704
[2022-10-10T19:25:24.035Z]    at DurableTask.Core.TaskActivityDispatcher.OnProcessWorkItemAsync(TaskActivityWorkItem workItem) in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 140
[2022-10-10T19:25:24.051Z]    at DurableTask.Core.TaskActivityDispatcher.OnProcessWorkItemAsync(TaskActivityWorkItem workItem) in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 263
[2022-10-10T19:25:24.069Z]    at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 45

Here's a screen shot...

![image](https://user-images.githubusercontent.com/50494751/194940220-a93ba968-8afb-449c-811a-46aa4a3a2878.png)

And I'm attaching my code.

Thanks in advance, I really appreciate the help,

Peter

[AmazonOrdersTrigger.cs.txt](https://github.com/Azure/durabletask/files/9748490/AmazonOrdersTrigger.cs.txt)

**Comment by cgillum** [comment]
Hmm...that's a confusing error message. Looking at the call-stack and based on my understanding of the Durable Functions internal code, my first guess is that you scheduled an activity function and later disabled that activity function. Could that possibly explain the problem?

Also, how are you deleting everything in storage, exactly? These errors would be driven by messages in the xxx-workitems queue.

**Comment by PeterAnaniaHC** [comment]
Sure, and thanks for you help.

First, with respect to deleting the activity data. I first deleted everything in the history, workitems and logs tables, and when that didn't work I deleted the entire storage account and started over. The issue still occurs! Even when there are no tables, queues or leases in the storage account. 

With respect to the app, I've implemented a fan in fan out pattern. I wrote a method that adds all of the activity functions to a List object, and I then do a Task.WhenAll() on that list.

I have a starter HTTP triggered function that calls the orchestrator and then the orchestrator calls the method that gets the list and it also calls the Task.WhenAll().

Is that what you were looking for?

Please  let me know

Peter

**Comment by cgillum** [comment]
If activities are running on startup, that means there are messages in the work-item queue from a previous debug session that haven't yet been fully consumed (maybe you stopped debugging mid-execution). You can either let them get fully consumed before stopping your debug session, which causes them to be individually deleted, or you could delete the work item queue to make 100% sure that you're starting with an empty queue.

**Comment by PeterAnaniaHC** [comment]
You've been incredibly helpful. I did exactly as you said and it responded exactly as you predicted. Thank you so much for your help! ~Peter

**Comment by cgillum** [comment]
Glad this was helpful!
