### ISSUE TITLE
DurableTaskStorageException: Value for one of the query parameters specified in the request URI is invalid

### ISSUE THREAD

**Issue by joerage** [Azure/durabletask#809]
We are running in an issue with DTFx. Sometimes (and only in one region where our service is running - WestEurope), when enqueuing a queue message to start an orchestration, the queueing fails because of a bad parameter in the query string.

Sample query: 
https://mystorage.queue.core.windows.net:443/devcenterjobs-control-00/messages?messagettl=%E2%88%921

Error and stacktrace:

> DurableTask.AzureStorage.Storage.DurableTaskStorageException: Value for one of the query parameters specified in the request URI is invalid.
>  ---> Microsoft.WindowsAzure.Storage.StorageException: Value for one of the query parameters specified in the request URI is invalid.
>    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
>    at DurableTask.AzureStorage.Storage.AzureStorageClient.WrapFunctionWithReturnType(Func`3 storageRequest, OperationContext context, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 158
>    at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId)
>    at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 149

Looking at the [code](https://github.com/Azure/durabletask/blob/eada7c1b64ea41edc78eb37133df46aefe294c1d/src/DurableTask.AzureStorage/Storage/Queue.cs#:~:text=TimeSpan%3F%20timeToLive,%23endif) here, the value of that param should always be -1 (we are not using NET462).

And looking at storage client [code](https://github.com/Azure/azure-storage-net/blob/cbe605f9faa01bfc3003d75fc5a16b2eaccfe102/Lib/ClassLibraryCommon/Queue/Protocol/QueueHttpRequestMessageFactory.cs#L187:~:text=public%20static%20StorageRequestMessage%20AddMessage,%7D), it should append it.

Any help to resolve this issue would be appreciated.

**Comment by davidmrdavid** [comment]
Thanks for reaching out @joerage. Just to be sure I understand this issue before jumping into it: you seem to emphasize the value of the message time-to-live, but nothing about the trace makes it immediately obvious to me why time-to-live may be at fault here. Can you please clarify this? Thanks!

**Comment by joerage** [comment]
Hi @davidmrdavid, I simply making this assumption because the call made to storage dataplane has a single query parameter:
https://mystorage.queue.core.windows.net:443/devcenterjobs-control-00/messages?messagettl=%E2%88%921

**Comment by davidmrdavid** [comment]
@amdeel - do you have any advice on this? Perhaps we can add some more telemetry here to confirm that `messagettl` is in fact the parameter that is invalid, as the exception doesn't make this fully clear. From there, the next steps in investigation would be clearer.

**Comment by jviau** [comment]
When you decode that URL, it does decode to `-1`: `%E2%88%921` == `-1`

If this is happening on only one region, is it an issue with Azure storage in that region? @joerage, can you try crafting a request with this that query param on it and sending it to different regions of Azure Storage? Asking because I imagine you have a few instances of Azure Storage readily available to test it out. If not, we can try that soon.

**Comment by joerage** [comment]
We found some more information since my last post. 

1. We saw the same encoding as you did. 
2. Every time the request to storage is sent without encoding, it is a valid request.
3. Every time the request to storage gets its param encoded, it fails with 400.
4. After all, it does not only happen in a single region. We have seen in some 8 regions. Although much more frequently in that single WestEurope region.
5. In 2 different cases, multiple HTTP requests were received by multiple services in multiple regions. These requests were all correlated to a single incoming request (from ARM; then RPaaS fanned them out to all our regions). And they all failed the same way!!
6. Only a few different customers are hitting this issue, but those customers see repeated such failures.

To your questions
1. Encoding only happens sometimes, but no idea why.
2. If param is encoding, they all fail, in all regions, otherwise it is good.
3. Omitting this param will use the default TTL of 7 days, instead of infinite.

**Comment by chrissmiller** [comment]
Not certain where the fix is, but the issue doesn't appear to repro on the newer Storage SDKs (e.g., Azure.Storage.Queues)

**Comment by davidmrdavid** [comment]
Wow, amazing find @chrissmiller! @amdeel, @jviau: do we think we could implement a similar or equivalent trick to ignore the user-specified CultureInfo when encoding our requests to Azure Storage?

**Comment by cgillum** [comment]
> do we think we could implement a similar or equivalent trick to ignore the user-specified CultureInfo when encoding our requests to Azure Storage?

We're in the process of migrating to modern versions of the Azure Storage SDK. Assuming the underlying issue is fixed there, it might make sense to just rely on the SDK upgrade rather than pushing a short-lived fix to work around issues in the deprecated SDKs.

**Comment by jviau** [comment]
I believe it is addressed in the newer SDKs.
