### ISSUE TITLE
Task result (failed) sometimes take very long to be processed

### ISSUE THREAD

**Issue by rafaeldnferreira** [Azure/durabletask#894]
Scenario: I've observed a longer retry for a task that is setup with a retry of 3 times - see logs attached; upon the first failure the task took more than one hour for its result to be processed, hence much longer to be re-attempted. (no node switch)

[Task-Result_taking_long_to_process.xlsx](https://github.com/Azure/durabletask/files/11333772/Task-Result_taking_long_to_process.xlsx)

The scenario is only visible on higher volumes where other issues are surfaced/being investigated - hence I can't confirm if this is because there are too many operations in place already disputing resources to run or a problem in orchestration framework itself.

I can confirm node resources (memory/cpu) are at normal levels.

Any guidance here is very much appreciated.

Core Version: 2.9
AzureStorage: 1.11.1

**Comment by cgillum** [comment]
I see you provided logs for `DurableTask-Core`, but in order to diagnose the problem, I think we'll need to look at the logs for `DurableTask-AzureStorage`. This can tell us more specific timings, such as when the response message was sent, when it was received, and whether any problems occurred before it was actually sent to the core engine to trigger the orchestration retry logic.

**Comment by rafaeldnferreira** [comment]
Thanks Chris, I will gather those and run a few traces on a fault node as well tomorrow.

**Comment by rafaeldnferreira** [comment]
Hi @cgillum , have a look on this new extraction: 

[send_receive_took_long.xlsx](https://github.com/Azure/durabletask/files/11346430/send_receive_took_long.xlsx)

There's a gap between receiving and start processing then the larger gap after sending the next message after the failure.

I'm leaning the investigation towards that the node is just too busy (because it does a lot of other kind of jobs, example serving API requests):

- I don't see problems in the lease tables and the control-queue is always the same;
- I don't see log entries indicating the process is being throttled (FetchingThrottled event) neither.

1) Would appreciate your thoughts - Do you see something relevant I don't in this set of logs?

2) I'm trying now to correlated what the node was doing (at least from a DTF perspective) using start/completed tasks logs, I don't have all the data in kusto so I'm doing some limited work on excel - is there an event/metric from DTF itself that would just give me such metrics? I can't guess one by looking to the ones defined in EventIds.cs

**Comment by rafaeldnferreira** [comment]
Hi @cgillum  - The best hint I got so far in this topic is that the contention is somewhere between the events FetchWorkItemStarting and FetchWorkItemCompleted - I see a huge spike in the LatencyMs for an observed period:

![image](https://user-images.githubusercontent.com/93147560/236529545-baf9e812-f27c-4822-ae09-00453d67fef8.png)

However I couldn't find anything in the AzureStorage relevant log events that would explain that, or I might not just correlating properly the events, I extracted one sample here: [Logs_Long_Latency_Observed.xlsx](https://github.com/Azure/durabletask/files/11409058/Logs_Long_Latency_Observed.xlsx)

I found there's a pattern/link in messages that have failed before - for example I found one bad message for an orchestration that doesn't exist that has been dequeue 19k times, however this affects both TaskActivityDispatcher and TaskOrchestrationDispatcher.

Scanning the code I can't see any logic that would cause huge backoffs like that ;
- I see an average number of storage requests in the stats at ~500 (which is the normal)
- No throtle;
- No lease changing / lease errors.

Appreciate if you or someone in the team would have further pointers / indications.

Thanks

**Comment by cgillum** [comment]
The long latency reported by `FetchWorkItemCompleted` means that it took a long time before we found the next message. This is not always a problem - this number could be high if the queue is simply empty for a long time. That's probably not the case for you though, so it would be interesting to dive a bit deeper. If there were errors reading the contents of the message or the orchestration history associated with that message, then that could explain this.

> I found one bad message for an orchestration that doesn't exist that has been dequeue 19k times, however this affects both TaskActivityDispatcher and TaskOrchestrationDispatcher.

Can you elaborate on this further?

**Comment by rafaeldnferreira** [comment]
HI @cgillum , the high number of dequeues are for items that are doomed to never complete, because the code no longer exists for those, see the extraction below, I've cleaned these messages and I could observe a better effect today.

![image](https://user-images.githubusercontent.com/93147560/237045472-07e42b49-7f9b-4692-9cf8-da80f48e3c00.png)

Does the exponential back off take these large dequeues into account and could explain these longer delays while transfering from controlQueue to workItem queue?

Thanks

**Comment by cgillum** [comment]
Just to confirm, you aren't seeing any errors in the `DurableTask-Core` logs? The only time you should be seeing backoff behavior that slows down orchestration processing is if there is an unhandled exception caught in the `DurableTask-Core` layer, in which case we should be logging it (as well as a message indicating that we're doing a backoff).

The high dequeue counts by themselves won't result in any throttling behavior. We'll defer those messages to a few minutes in the future but will still process any other queue messages immediately (assuming we're not throttling).

**Comment by rafaeldnferreira** [comment]
HI,

I do see errors from these bad messages surely, they come in two patterns:

1) The one about orchestrations that no longer exists in the code base:

`DurableTask.Core.Exceptions.TypeMissingException: Orchestration not found: (RotateDekOrchestrator, V1)
   at DurableTask.Core.TaskOrchestrationDispatcher.<>c__DisplayClass24_0.<ExecuteOrchestrationAsync>b__0(DispatchMiddlewareContext _) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 590
   at DurableTask.Core.TaskOrchestrationDispatcher.ExecuteOrchestrationAsync(OrchestrationRuntimeState runtimeState, TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 612
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 560
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 276
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 459

Backing off for 10 seconds`

2) The second which I think it is because the same message potentially got dequeued twice (I confirm there isn't any Lease error nor Node switch - it is all under the same process in the same node)

```
DurableTask.AzureStorage.Storage.DurableTaskStorageException: Element 5 in the batch returned an unexpected response code.
 ---> Microsoft.WindowsAzure.Storage.StorageException: Element 5 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId) in /_/src/DurableTask.AzureStorage/TimeoutHandler.cs:line 143
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 149
Request Information
RequestID:c7a271b6-e002-0065-2dc7-79a43d000000
RequestDate:Fri, 28 Apr 2023 11:51:00 GMT
StatusMessage:5:The specified entity already exists.
ErrorCode:
ErrorMessage:5:The specified entity already exists.
RequestId:c7a271b6-e002-0065-2dc7-79a43d000000
Time:2023-04-28T11:51:01.2661576Z

   --- End of inner exception stack trace ---
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 149
   at DurableTask.AzureStorage.Storage.Table.ExecuteBatchAsync(TableBatchOperation batchOperation, String batchType) in /_/src/DurableTask.AzureStorage/Storage/Table.cs:line 187
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UploadHistoryBatch(String instanceId, String sanitizedInstanceId, String executionId, TableBatchOperation historyEventBatch, StringBuilder historyEventNamesBuffer, Int32 numberOfTotalEvents, Int32 episodeNumber, Int32 estimatedBatchSizeInBytes, String eTagValue, Boolean isFinalBatch) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 1250
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 1024
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1081
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 560
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 276
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 459

Backing off for 10 seconds until 5 successful operations
```

The fact I haven't given that much credit to these errors so far is that their rate is very low compared to the delays I'm observing, see how many they were showing in the logs over a day (Exceptions X minute):

![image](https://github.com/Azure/durabletask/assets/93147560/7ae365f6-ebf2-4ba4-a1a6-eac93c52861e)

However, since yesterday after I've purged the control queues and these bad messages are no longer being attempted to be processed, we are experiencing much better results - delays are significantly lower - I will post here by EOD or tomorrow a comparison so you can get a sense of scale.

Is there a feature that I can turn on and make these bad messages being moved to DLQ for later inspection rather than being scheduled for a future execution ?

**Comment by cgillum** [comment]
We unfortunately don't have a DLQ (poison message handling) feature right now, though it's something we're regularly evaluating.

/cc @lilyjma

**Comment by rafaeldnferreira** [comment]
That's something I would be really keen to contribute at design / operation level. Is there a feature request tracking it ?

**Comment by cgillum** [comment]
@rafaeldnferreira We have some discussion of this problem here: https://github.com/Azure/durabletask/issues/553. One thing that we need help coming to agreement on is what kind of policies we should support, and what are the implications of those policies. Happy to hear your thoughts on this matter.
