### ISSUE TITLE
Method "ForceTerminateTaskOrchestrationAsync" throwing error 

### ISSUE THREAD

**Issue by Najjaf** [Azure/durabletask#939]
Hi, We were using durable task framework in one of our projects having NET Framework 4.6.2 from past few years and it was working fine.
Now, we decided to upgrade .NET version from framework to .NET 6.0. After the upgrade, we found out that Termination functionality is not working as expected and throwing an error that "Operation is not valid due to the current state of the object."

Below is the stack trace,

`   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Monitoring.Controllers.HomeController.TerminateOrchestration(OrchestrationEntity orchestration, String terminationMessage) in D:\Repos\Monitoring\Controllers\HomeController.cs:line 412
   at Monitoring.Controllers.HomeController.TerminateOrchestration(OrchestrationTerminateContext model) in D:\Repos\Monitoring\Controllers\HomeController.cs:line 359
`

The complete code is below,

`public class Test
{
private readonly TaskHubClient _taskHubClient;

        private readonly IResourceCreator _resourceCreator;

 public Client(string serviceBus, string taskHubName, string azureStorageTableName,
            string azureStorageAccount, string jumpStartTableName
            , IOrchestrationLookupController<T> orchestrationLookupController)
        {
            _resourceCreator = new AzureResourceCreator(serviceBus, azureStorageAccount, taskHubName);
            _resourceCreator.CreateResources();

            _taskHubClient = new TaskHubClient(_resourceCreator.OrchestrationServiceAndClient);

        }

public bool TerminateOrchestration(string instanceId, string terminationMessage)
        {
            if (string.IsNullOrWhiteSpace(instanceId))
            {
                return false;
            }

            AsyncContext.Run(() =>
                _resourceCreator.OrchestrationServiceAndClient.ForceTerminateTaskOrchestrationAsync(instanceId,
                    terminationMessage));

            return true;
        }

}
`

It started throwing error in .NET 6.0 but working fine in .Net framework

**Comment by cgillum** [comment]
Your call stack only includes code from your project (`Monitoring.Controllers.HomeController`). Are you sure this exception is coming from the Durable Task Framework?

**Comment by Najjaf** [comment]
Hi @cgillum, thanks for responding. I have updated the complete stack trace for reference also added the DurableTaskFramework code flow where actually exception occurs. The below method inside "DurableTask.ServiceBus.ServiceBusOrchestrationService.cs"  is causing exception to occur,

` public Task SendTaskOrchestrationMessageAsync(TaskMessage message)
        {
            return SendTaskOrchestrationMessageBatchAsync(message);
        }
`
